spring.application.name=code

spring.datasource.url=jdbc:mysql://172.21.178.253/inventory?usessl=false
spring.datasource.username=root

spring.datasource.password=u8Y6THXQJVfAYkCK5XZ14pRT
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:EcyzZjlPaOogCam9Ixvpv7nl@172.21.7.218:27017/reviews?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true

 