spring.application.name=code

spring.datasource.url=jdbc:mysql://172.21.67.161/inventory?usessl=false
spring.datasource.username=root

spring.datasource.password=enPQmIh2f2YsOVTT6vc8ZTWa
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:7PXH5mzS4rlFk2csV6HOghTa@172.21.145.59:270177/reviews?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true

 